SPO-13135 Поиск пользователей
ingvilow/test_provider_2 pull request #8
Opened 2022-05-16 06:22 UTC by ingvilow

2022-05-16 09:29 UTC, arefimenko commented on lib/search_widget/widget/search_bar_widget.dart
> +  final Function()? onClear;
_минор_ можно использовать `VoidCallback`

2022-05-16 09:29 UTC, arefimenko commented on lib/search_widget/widget/search_bar_widget.dart
> +    required this.onClear,
`onClear` сделан nullable в данный момент, в таком случае `required`, на мой взгляд, не имеет смысла (+ нажатие нам явно важно обработать, смею предположить что nullable его не стоит делать), а вот `onChanged` может быть таковым

2022-05-16 09:29 UTC, arefimenko commented on lib/widgets/users_list_wm.dart
> +  }
состояние найденных пользователей зачистилось, а текст в поле ввода скорее всего нет - это тоже нужно сделать

2022-05-16 09:29 UTC, arefimenko commented on lib/widgets/users_list_wm.dart
> +
состояния для ui было бы неплохо называть в конце с `State` суффиксом, аля `searchUsersState`, `usersState` и так далее

2022-05-16 09:47 UTC, ingvilow commented on lib/widgets/users_list_wm.dart
> +
+

2022-05-16 09:50 UTC, ingvilow commented on lib/search_widget/widget/search_bar_widget.dart
> +    required this.onClear,
+

2022-05-16 09:50 UTC, ingvilow commented on lib/search_widget/widget/search_bar_widget.dart
> +  final Function()? onClear;
+

2022-05-17 12:41 UTC, arefimenko requested changes
при зачистке поля ввода не происходит сброс состояния найденных пользователей

2022-05-18 09:52 UTC, arefimenko approved these changes

2022-05-20 06:06 UTC, maxim-sysoev commented on lib/widgets/users_lists_screen.dart
> +            ),
На айфонах начиная с x (там где safe area ещё и снизу) стоит добавлять отступ в паддинг скролла, иначе возникает ситуация используется не весь экран (список обрезается)
<img width="350px"  src="https://honesdev.com/images/flutter/custom-scroll.gif"/>

добавить паддинг в скролл можно указав соответствующее поле у виджета скролла:
`padding: MediaQuery.of(context).veiwInsets.bottom`

2022-05-20 06:06 UTC, maxim-sysoev commented on lib/widgets/users_lists_screen.dart
> +          return const Center(child: Text('err'));
желательно добавить кнопку перезагрузить

2022-05-20 06:06 UTC, maxim-sysoev commented on lib/widgets/users_lists_screen.dart
> +          return const Center(child: Text('err'));
желательно добавить кнопку перезагрузить

2022-05-20 08:43 UTC, ingvilow commented on lib/widgets/users_lists_screen.dart
> +          return const Center(child: Text('err'));
Тогда тут  будет перезагрузка списка пользователей, а не поиска пользователей

2022-05-20 09:47 UTC, maxim-sysoev commented on lib/widgets/users_lists_screen.dart
> +          return const Center(child: Text('err'));
а иначе поиск всё равно не отобразится, типо у нас будет на весь экран надпись "ошибка" и больше ничего

2022-05-20 09:56 UTC, maxim-sysoev commented on lib/widgets/ui/list_result.dart
> +class ListResult extends StatelessWidget {
название класса не очень отображает суть, в этом виджете только один элемент из списка

2022-05-20 09:57 UTC, maxim-sysoev commented on lib/widgets/ui/list_result.dart
> +class ListResult extends StatelessWidget {
_минор_ такие мелкие классы можно поместить в файл с основным ui

2022-05-20 10:14 UTC, maxim-sysoev approved these changes

2022-05-23 08:11 UTC, merged